apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  generation: 3
  name: letsencrypt-prod
spec:
  acme:
    email: imam.arief.rhmn@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            class: nginx