kind: Secret
apiVersion: v1
metadata:
  name: demo-s3-keys
  namespace: eck
data:
  access-key: QUrJQVU2UzY0bzY1U0NMTlJPSk8=
  secret-key: WTBrMW6Tb3k0Z1hOMlJxdHdQOTBCRU31RU16VURpZTdpOUg2SlVSTw==
type: Opaque
